#----------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: starwars-hyperservice-microservice
  namespace: back
spec:
  ports:
  - name: http
    protocol: TCP
    port: 3001
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starwars-hyperservice-microservice
  namespace: back
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      microService: starwars-hyperservice-microservice
  template:
    metadata:
      labels:
        microService: starwars-hyperservice-microservice
        version: v1.0.0
    spec:
      containers:
      - name: starwars-hyperservice-microservice
        image: frankieem/starwars-hyperservice:latest-BACK
        imagePullPolicy: Always
        ports:
        - containerPort: 3001    

          #-----------------------------------------------
